== Android  - Quick Guide
:toc:
:toclevels: 3
:sectnums: 3
:sectnumlevels: 3
:icons: font
:source-highlighter: rouge


.Links
- https://developer.android.com/tools/adb[adb]
- https://psabadac.medium.com/ssh-adb-9d92c676d8c0[ssh + adb + scrcpy = â¤]

=== Android SDK

=== Android Configs

.Android Phone/Tablet Settings
- Enable USB Debugging Mode


=== `adb` - Android Debug Bridge

.Connect using IP Address
- On your Android device -> Enable USB Debug Mode
- On your machine -> run `adb devices` . This should list connected android devices
- Restart adb service -> run `adb tcpip 5555`
- connect `adb connect 192.168.1.3:5555`


.Connect using IP Address
----
adb connect 192.168.1.6:5555
adb -s 192.168.1.3:5555 shell
adb disconnect 192.168.1.6:5555
----

=== `scrcpy` - Screen Sharing

NOTE: Use refer to how to connect adb over tcpip!

.Connect Using Ip Address
----
scrcpy --tcpip=192.168.1.6:5555
----

.Connect with Max Resolution
----
scrcpy --tcpip=192.168.1.6:5555 --max-size=2800
----



=== Data Backup and Sync

.Not the official adb
- https://github.com/google/adb-sync[adb-sync]



.Inner Storage? - /storage/self/primary/
 adb -s 192.168.1.3:5555 pull --sync -a /storage/self/primary

.External Storage? - /storage/0000-0000/
 adb -s 192.168.1.3:5555 pull --sync -a /storage/0000-0000/





















=== WayDroid




.install
----
curl -s https://repo.waydro.id | sudo bash

sudo apt install waydroid -y
----

.init
----
sudo waydroid init -f -s GAPPS #Google App
sudo waydroid init -f -s VANILLA
----













----
sudo systemctl restart waydroid-container.service
waydroid session start
----


.Uninstall
----
waydroid session stop
sudo waydroid container stop

sudo apt purge waydroid

sudo rm -rf /var/lib/waydroid /home/.waydroid ~/waydroid ~/.share/waydroid ~/.local/share/applications/*aydroid* ~/.local/share/waydroid
----

.Re-Init
----
sudo waydroid init -f -s GAPPS
----


----
waydroid prop set persist.waydroid.multi_windows true
waydroid prop set persist.waydroid.width 1920
waydroid prop set persist.waydroid.height 2000

waydroid prop get persist.waydroid.width
waydroid prop get persist.waydroid.height
----


----
waydroid show-full-ui
----

==== Install APK Apps


.Verify APKs
----
apksigner verify -v --print-certs --min-sdk-version 24
----

.Install apksigner
Install -> Android SDK Build-Tools

.F-Droid
https://f-droid.org/F-Droid.apk

.Brave
https://github.com/brave/brave-browser/releases/download/v1.73.89/BraveMonox64.apk

.DuckDuckGo
https://github.com/duckduckgo/Android/releases/download/5.220.0/duckduckgo-5.220.0-play-release.apk

.Signal
----
wget https://updates.signal.org/android/Signal-Android-website-prod-universal-release-7.23.1.apk

waydroid app install Signal-Android-website-prod-universal-release-7.25.0.apk
----















=== Android SDK & Studio

.install
----

----

NOTE: It uses `qemu-kvm`

.uninstall
----

----



.Create an Emulator
----

----

.Navigate Emulator Dir
----

----


.Webcam Troubleshooting
----

----

.Install APK via adb
----

----

 ANDROID_SDK_HOME=/opt/_langs/android/sdk/; $ANDROID_SDK_HOME/emulator/emulator -list-avds

 $ANDROID_SDK_HOME/emulator/emulator -list-avds
 $ANDROID_SDK_HOME/emulator/emulator -avd Small_Phone_API_34