= Developer's Guide to Data Mining - `jq` `yq` `xq` `hq`
Haze Wylde
:toc:
:toclevels: 3
:sectnums: 3
:sectnumlevels: 3
:icons: font
:source-highlighter: rouge

== Data Mining - HTMLQuery `hq`

== Data Mining - XMLQuery `xq`

== Data Mining - YAMLQuery `yq`

== Data Mining - JSONQuery `jq`

[source,bash]
.Restructure Output of `ls -al` into a JSON
----
{(echo -e 'c1 c2 c3 c4 c5 c6 c7 c8 c9' & (ls -al ../ | tail -n +2)) } | cat - |
  tr -s ' ' |
    jq -Rcn '
    input   | split(" ")  as $header |
    inputs  | split(" ") |
                    to_entries |
                            map(.key = $header[.key]) | .[0:] | from_entries'
----

[source,bash]
.Restructure Output of Text file into a JSON - Feed to `wget`
----
{(echo -e 'url filename' & (cat url-filename.txt)) } | cat - |   tr -s ' ' |     jq -Rcn '
    input   | split(" ")  as $header |
    inputs  | split(" ") |
                    to_entries |
                            map(.key = $header[.key]) | .[0:] | from_entries' | jq -r '"\(.filename) \(.url)"' | xargs -L 1 bash -c  'wget -O $0 $1'
----

[source,bash]
.Print Path and Key Values of a JSON
----
cat somejson.json | jq -r 'paths(scalars | true) as $p  | [ ( [ $p[] | tostring ] | join(".") ), ( getpath($p) | tojson )] | join(": ")'
----

=== jq xq xml html json

- convert html/xml to json

[source,bash]
.print flattened json _keys_ PATHs
----
cat xml-file.xml | xq -r | jq -r 'paths(scalars | true) as $p  | [ ( [ $p[] | tostring ] | join(".") )] | join("")'
----

[source,bash]
.print flattened json _key:val_ PATHs
----
 cat xml-file.xml | xq -r | jq -r 'paths(scalars | true) as $p  | [ ( [ $p[] | tostring ] | join(".") ), ( getpath($p) | tojson )] | join(": ")'
----

.remove null - [RED]#NOT# working as expected
[source,bash]
----
walk(
    if type == "array" then
      map(select(. != null))
    elif type == "object" then
      with_entries(
        select(
          .value != null and
          .value != "" and
          .value != [] and
          .value != {}
        )
      )
    else
      .
    end
  )
----

[source,bash]
.remove null - [GREEN]#Working#
----
walk( if type == "array" then map(select(length > 0)) elif type == "object" then with_entries( select( .value != null and .value != "" and .value != [] and .value != {} ) ) else select(.) end )

----

.Extract/Validate JSON Schema from Source - `JESS`
 JESS --schema schema.json payload.json

- Link: https://github.com/pkoppstein/JESS
- Link: https://gist.github.com/pkoppstein/a5abb4ebef3b0f72a6ed[schema.jq]

.https://jqlang.org/manual/#error-suppression-optional-operator[Error Suppression]
NOTE: The `?` operator, used as *EXP?*, is shorthand for *try EXP*

.Example of using `?`
----
Command:    jq '[.[] | tonumber?]'
Input:      ["1", "invalid", "3", 4]
Output:     [1, 3, 4]
----

=== RegEx Operations - `jq`

NOTE: Reference: https://jqlang.org/manual/#regular-expressions[JQLang -> RegEx]

* Filter With - `test`
+
.Run Filter `test`
[source,bash]
----
echo 'name:Hazy Hazel Watching You|number:0123456789' \
  | jq -Rr '. | test("name:(?<n1>[a-zA-Z ]+)")'
----
+
.Output `test`
[source,json]
----
true
----






* Filter With - `match`
+
.Run Filter `match`
[source,bash]
----
echo 'name:Hazy Hazel Watching You|number:0123456789' \
  | jq -Rr '. | match("name:(?<n1>[a-zA-Z ]+)")'
----
+
.Output `match`
[source,json]
----
{
  "offset": 0,
  "length": 28,
  "string": "name:Hazy Hazel Watching You",
  "captures": [
    {
      "offset": 5,
      "length": 23,
      "string": "Hazy Hazel Watching You",
      "name": "n1"
    }
  ]
}
----






* Filter With - `capture`
+
.Run Filter `capture`
[source,bash]
----
echo 'name:Hazy Hazel Watching You|number:0123456789' \
  | jq -Rr '. | capture("name:(?<n1>[a-zA-Z ]+)[|]number:(?<n2>[0-9]+)")'
----
+
.Output `capture`
[source,json]
----
{
  "n1": "Hazy Hazel Watching You",
  "n2": "0123456789"
}
----






* Filter With - `sub`
+
.Run Filter `sub`
[source,bash]
----
echo '                name:Hazy Hazel Watching You' \
  | jq -Rr '. | sub("^[ ]+"; "")'
----
+
.Output `sub`
[source,text]
----
name:Hazy Hazel Watching You
----

TIP: Use `sub` to remove trailing whitespaces

// ToDo - Add Content
=== referencing with Variables and Identifiers - `. | as $varname`

