= Git - Quick Guide (_Incomplete_)
Husain AK
:toc:
:toclevels: 3
:sectnums: 3
:sectnumlevels: 3
:icons: font

== Configs
.Creating an Alias
 $ git config --global alias.hist "log --pretty=format:'%h %ad |%s%d [%an]' --date=short"

The above alias can be called just like a regular command:

 $ git hist


.Removing/Unsetting an Entry
 $ git config --global --unset alias.hist

.Setting editor 'vim'
 $ git config --global core.editor "vim"


== Remotes
=== Adding Multiple Remotes

The goal is to commit the new changes into a new remote repository (_Keybase in my case_) and leave the current (_GitHub in my case_) intact.

NOTE: create the destination repo first

.Remote (Destination)
 $ git clone keybase://private/username/your-repo ./your-repo

.Remote (Source)
 $ git checkout -b kb-branch
 $ git commit -m "your message"
 $ git remote add kb keybase://private/username/your-repo
 $ git fetch --all -v
 $ git push -u kb master
 $ git branch --set-upstream-to=kb/master kb-branch
 $ git pull -v

You're all set. +
If you check the remote Keybase repo you will find all your changes were pushed.

=== Pull/Push to/from Multiple Remotes

.Fetch from all remotes
 $ git fetch --all -v

.Pull changes from remote "kb" @branch "master"
 $ git pull kb master -v

.Pull changes from remote "origin" @branch "master"
 $ git pull origin master -v

== Syncing (Remote <- -> Local)
=== Syncing Remote with Local

.Removing remote branch after it was removed from local
 $ git ???

.Adding remote branch after it was added to local
 $ git ???


=== Syncing Local with Remote

.Removing local branch after it was removed from remote
 $ git ???

.Adding local branch after it was added to remote
 $ git ???

.https://www.freecodecamp.org/news/how-to-delete-a-git-branch-both-locally-and-remotely/[Link]
TIP:    Try to synchronize your branch list using: +
        `git fetch -p` +
        The -p flag means "prune". +
        After fetching, branches which no longer exists on the remote
        will be deleted.

== Squashing Commits

.Using `rebase`
----
git rebase -i HEAD~3
git push origin master --force
----

.When merging
----
git merge some_branch --squash
----

== Merge Conflict

=== Resolution
=== Avoidance Strategy

== Stashing & Popping

- Link: https://www.atlassian.com/git/tutorials/saving-changes/git-stash[git-stash]


----
git stash
----

.List all stashes
----
git stash list
----

.Diff with a Stash
----
git stash show [-p]
----


.Unstashing
----
git stash apply [stash@{0|1|..}]
git stash drop [stash@{0|1|..}]
git stash pop [stash@{0|1|..}] <- (apply + drop)
----


.Creating a branch from your stash
----
git stash branch add-stylesheet stash@{1}
----

== Strategies and Best Practices
=== Syncing Other's with Forked
