= Git Guide (_Incomplete_)
Husain AK
:toc:
:toclevels: 3
:sectnums: 3
:sectnumlevels: 3
:icons: font

== Configs
.Creating an Alias
 $ git config --global alias.hist "log --pretty=format:'%h %ad |%s%d [%an]' --date=short"

The above alias can be called just like a regular command:

 $ git hist


.Removing/Unsetting an Entry
 $ git config --global --unset alias.hist


== Repositories
=== Local
=== Remote

=== Adding Multiple Remotes

The goal is to commit the new changes into a new remote repository (_Keybase in my case_) and leave the current (_GitHub in my case_) intact.

NOTE: create the destination repo first

.Remote (Destination)
 $ git clone keybase://private/username/your-repo ./your-repo

.Remote (Source)
 $ git checkout -b kb-repo
 $ git commit -m "your message"
 $ git remote add kb keybase://private/username/your-repo
 $ git fetch --all -v
 $ git push -u kb master
 $ git branch --set-upstream-to=kb/master kb-repo
 $ git pull -v

You're all set. +
If you check the remote Keybase repo you will find all your changes were pushed.

=== Pull/Push to/from Multiple Remotes

.Fetch from all remotes
 $ git fetch --all -v

.Pull changes from remote "kb" @branch "master"
 $ git pull kb master -v

.Pull changes from remote "origin" @branch "master"
 $ git pull origin master -v



== Merge Conflict

