:toc:
:toclevels: 3
:sectnums: 3
:sectnumlevels: 3
:icons: font
:source-highlighter: rouge

= Linux Commands Guide (_Incomplete_)
Hazy Wylde

include::tools-brave.adoc[]

include::tools-pandoc.adoc[]

include::tools-gnome.adoc[]

include::tools-asciidoctor.adoc[]






== Random - Quick guide


=== OpenSSL

.todo
 openssl req -x509 -nodes -days 365 -newkey rsa:1024  -keyout vsftpd.pem  -out vsftpd.pem

.generate a self-signed certificate:
 openssl req -new -x509 -nodes -days 10000 -out server.crt -keyout server.key

.encrypt the private key by passing a “pass phrase”
 openssl rsa -des3 -in server.key -out server.key

.What are these?
- Squid Proxy Server
- visible_host hsmaklinux

- http://tldp.org/HOWTO/TransparentProxy.html

[source,bash]
----
http_port hsmaklinux:3128 transparent
IF_WAN="eth0"
iptables -t nat -A POSTROUTING -o $IF_WAN -j MASQUERADE
iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 80 -j REDIRECT --to-port 3128
----

=== Data Backup & Recovery

- https://help.ubuntu.com/community/DataRecovery

 sudo foremost -v -t jpg -i /dev/hda -o /recovery/foremost

- Ubuntu OS Backup & Recovery

.Backup
 dd if=/dev/sda of=/mnt/LocalDrive/Ubuntu9.04_Backup_20090625.img conv=noerror,sync bs=4M

.Recovery
 dd of=/dev/sdc if=/mnt/LocalDrive/Ubuntu9.04_Backup_20090625.img bs=4M


.ToDo
 sudo tune2fs -U random /dev/sdc1

.get the new UUID from:
 sudo blkid

.modify UUID in the following files accordingly:
----
/etc/fstab
/boot/grub/menu.list
----

=== Booting an Ubuntu Drive Image

IMAGE_NAME=ubuntu-drive.img

NOTE: same commands can be used with a loopback device without mounting - see `losetup`

.`parted`
----
parted $IMAGE_NAME unit B print
----

.Output
----
Number  Start       End            Size           Type      File system  Flags
1      1048576B    537919487B     536870912B     primary   fat32        boot
2      538967040B  525112180735B  524573213696B  extended
5      538968064B  525112180735B  524573212672B  logical   ext4
----

.`mount` with an offset
----
sudo mount -v -m -o loop,rw,offset=538968064 $IMAGE_NAME /mnt/rabbit
----

=== run `fsck`/`e2fsck` on a loopback device/image - `losetup`

.link
* https://unix.stackexchange.com/questions/413991/fsck-at-boot-time-for-loopback-device
* https://unix.stackexchange.com/questions/418322/persistent-lvm-device-with-loopback-devices-by-fstab/421414#421414
* https://commandmasters.com/commands/losetup-linux/


.list loopback devices
----
sudo losetup --all
sudo losetup --list --json
sudo losetup --list --output-all
----

.create a loopback device - without mounting
----
sudo losetup --show --partscan -f $IMAGE_NAME
----


fix filesystem errors - `fsck`
----
sudo fsck.ext4 -y /dev/loopXYpZ
----


.Detach
----
sudo losetup -d /dev/loopXY
----


=== Resize (Shrink/Expand) Partition - no data loss

* fdsik
* sfdisk
* parted
* partx
* partprobe
* growpart
* e2fsck/fsck
* resize2fs
* cryptsetup-resize

CAUTION: Never modify partitions while mounted!

.resize2fs
NOTE: The `resize2fs` program does not manipulate the size of partitions.


.If you wish to enlarge a file system: Always start with the partition table then the filesystem
* you must make sure you can expand the size of the underlying partition first.
* After running `fdisk`/`parted`, run `resize2fs` to resize the ext2 file system to use all of the space in the newly enlarged partition.

.If you wish to shrink an ext2 partition,
* first use `resize2fs` to shrink the size of file system.
* Then you may use `fdisk`/`parted` to shrink the size of the partition.
* When shrinking the size of the partition, make sure you do not make it smaller than the new size of the ext2 file system!


.Order of Commands - Shrink: Always start with the filesystem then the partition table
. sudo e2fsck -fy /dev/sdXY
. sudo resize2fs -M /dev/sdXY
. sudo parted /dev/sdX resizepart 1 SIZE_X


.Order of Commands - Expand
. sudo parted /dev/sdX resizepart 1 SIZE_X
. sudo e2fsck -fy /dev/sdXY
. sudo resize2fs -Mp /dev/sdXY



----
sudo e2fsck -fy /dev/sdXY
# sudo resize2fs -M /dev/sdXY
sudo resize2fs -p /dev/sdXY 200GB # make sure it's a bit more than actual data size
----

----
sudo parted /dev/sdX
resizepart 1 200G
----

----
sudo fdisk /dev/sdX
n
----


==== Resize Partitions By Merging

.Options:
* LEFT Merge: data must be moved to the left by copying/cloning
    ** `dd` can be useful but caution to be
* RIGHT Merge

.links
* https://agix.com.au/expand-a-luks-encrypted-volume/
* https://help.ubuntu.com/community/ResizeEncryptedPartitions
* https://unix.stackexchange.com/questions/320957/extend-a-luks-encrypted-partition-to-fill-disk


----
sudo cryptsetup --debug --verbose open /dev/mapper/VOLUME_NAME VOLUME_NAME
sudo fdisk /dev/sdX
> delete partition
> While maintaining the the same starting sector of the partition in mind,
> recreate with size in mind.
sudo cryptsetup --debug --verbose resize VOLUME_NAME
sudo e2fsck -fyv /dev/mapper/VOLUME_NAME
sudo resize2fs -p /dev/mapper/VOLUME_NAME
----





==== Rearrange the Order of a Partition - `parted`

.parted - print help menu
----
sudo parted /dev/sdc  unit s help
----

parted - Note down the START/END Sectors of the intended partitions
----
sudo parted /dev/sdc --json unit s print free
sudo parted /dev/sdc --json unit s print
----


.parted - Recreate the partitions in the desired order
----
sudo parted /dev/sdc --json unit s rm 2
sudo parted /dev/sdc --json unit s mkpart ext4 4194304 419430399
----






Resize the LUKS Volume

.Calculate the new size using the formula:
----
NEW_LUKS_SECTOR_COUNT = (PV_EXTENT_COUNT * PV_EXTENT_SIZE) / LUKS_SECTOR_SIZE
----

.Then resize the LUKS volume:
----
cryptsetup -b NEW_LUKS_SECTOR_COUNT resize cryptdisk
----

----
NEW_PARTITION_SECTOR_END = PARTITION_SECTOR_START + (LUKS_SIZE_SECTORS + LUKS_OFFSET_SECTORS) - 1
----








=== Partitioning & Format

.links
* https://help.ubuntu.com/community/InstallingANewHardDrive
* https://sysadminsage.com/resize-a-partition-linux/
* https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9/html/managing_storage_devices/getting-started-with-partitions_managing-storage-devices#proc_resizing-a-partition-with-parted_getting-started-with-partitions
* https://bbs.archlinux.org/viewtopic.php?pid=2178377#p2178377

.Alignment
* 4K alignment?
* MiB Alignment?

.4K alignment
NOTE: You can verify if partitions are 4K aligned using commands like fdisk -l or parted.
Look for the starting sector of each partition to ensure it is a multiple of 8 (since 4K = 8 sectors of 512 bytes).


PART_START/(512*8)
PART_END-1/(512*8)



 sudo fdisk /dev/sdb

.then:
- d:   delete a partition
- n:   add a new partition
- w:   write table to disk and exit

 sudo mkfs -t ext3 /dev/sdb1  “for file system type: ext3”

.or
 sudo mke2fs /dev/sdb1


.mount a partition from a hard drive image
- http://www.andremiller.net/content/mounting-hard-disk-image-including-partitions-using-linux

.extract boot record from Window ISO
- http://linuxtuneup.blogspot.com/2006/01/slipstreaming-windows-cd-under-linux.html

.making bootable windows iso images
- http://linuxtuneup.blogspot.com/2006/01/slipstreaming-windows-cd-under-linux.html
- http://users.telenet.be/mydotcom/howto/boot/bootcd_win.htm

.For Windows 7 img udf
- http://forums.opensuse.org/english/get-technical-help-here/applications/460308-making-bootable-iso-dvd-virtualbox.html

. Use dd to make an image copy of the DVD to an image file

 > dd if=/dev/sr0 of=windows7.img

. Use geteltorito (in openSUSE, this is in the genisoimage package) to extract the boot binary image

 > geteltorito windows7.iso > boot.bin
+
----
Booting catalog starts at sector: 22
Manufacturer of CD: Microsoft Corporation
Image architecture: x86
Boot media type is: no emulation
El Torito image starts at sector 735 and has 8 sector(s) of 512 Bytes
Image has been written to stdout ….
----

. Make a directory to store the contents of the ISO

 > mkdir windows7ISO

. Mount the image file to copy the contents
+
----
> su
# mkdir /mnt/dvd
# mount windows7.img /mnt/dvd -o loop
# exit
> cp -r /mnt/dvd/* windows7ISO
> chmod -R 754 windows7ISO
----

. Copy boot.bin to the new ISO directory

 > cp boot.bin windows7ISO

. Make the ISO

 mkisofs -udf -b boot.bin -no-emul-boot -hide boot.bin -relaxed-filenames -joliet-long -D -o windows7.iso windows7ISO

. windows7.iso is your new bootable ISO




















//ToDo - Move to scripts-sandbox
=== Fan Control for Dell
- control cpu fan speed and temperature

.a script to control the fans (shared by someone):
[source,bash]
----
#!/bin/bash
### BEGIN INIT INFO
# Provides:          fanCtrl
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     1 2 3 4 5
# Default-Stop:      0 6
# Short-Description: Start fan control at boot time
# Description:       Enable service provided by fanCtrl.
### END INIT INFO

# Records the CPU temp and writes it to a temporary file.
tempCPU=0

constMaxTemp=40

fanHI=false
fanLO=false

while [ 1 ]; do
var=($(sensors | grep "Core" | sed 's/.*:\s*+\(.*\)  .*(.*/\1/' | sed 's/[°C]//g' | sed 's/\.0//g'))

	for i in {0..11} ; do
		if [[ ${var[i]} -gt $tempCPU ]]; then
			tempCPU=${var[i]}
		fi
	done

	if [[ $tempCPU -gt $constMaxTemp ]]; then
		if [[ "$fanHI" -eq false ]] ; then
			eval "i8kfan 2 2"
			fanHI=true
			fanLO=false
#			echo 'temp is high'
		fi
	else
		if [[ "$fanLO" -eq false ]] ; then
			eval "i8kfan 1 1"
			fanHI=false
			fanLO=true
#			echo 'temp is low'
		fi
	fi

	tempCPU=0;

sleep 1;
done
----
.place the above file in the dir:
 /usr/local/bin

.create a startup config file to be loaded by systemd:
file name: fanctl.service:
[Unit]
Description="Job that increases cpu fans when core temperature reaches 40C"

[Install]
WantedBy=multi-user.target

[Service]
Restart=always
ExecStart=/usr/local/bin/fanctl.sh
place the above in the dir:
/lib/systemd/system

run the command to anable bootup run
> sudo systemctl enable fanctl

reboot the machine


=== Archive | Create | Extract | Split with - `tar` & `split`

- Link: https://unix.stackexchange.com/questions/61774/create-a-tar-archive-split-into-blocks-of-a-maximum-size[create-a-tar-archive-split-into-blocks-of-a-maximum-size]

.Create and Split an Archive
 tar cvzf - dir/ | split -b 200m - sda1.backup.tar.gz.

.Merge splits into one archive
 cat sda1.backup.tar.gz.* | tar xzvf -

=== Sync Dirs with - `rsync`

.Syncing dirs
 rsync -avzhruP --delete src_dir dst_dir

.Dry Run
TIP: add `-n` for dry run.


=== Find Files/Dirs with - `find`

==== With `-type f` & `-regextype posix-extended`
.Find jar files ending with [`-javadoc.jar` | `-sources.jar` | ...]
 find ~/.m2/repository/org/apache/ -type f -regextype posix-extended -regex '^[./].*[-][a-z]+[.]jar$' | sort -d

.Find jar files ending with [`.1.jar` | `.12.jar` | ...]
 find ~/.m2/repository/org/apache/ -type f -regextype posix-extended -regex '^[./].*[.][0-9]+[.]jar$' | sort -d

.Find | Grep
 find ~/.m2/repository/ -type f -regextype posix-extended -regex '^[./].*[.][0-9]+[.]jar$' | sort -d | grep -Eo '([-.a-z+_0-9+\]+[0-9.]+).jar$' | grep -Eo '([-.a-z+_0-9+\]+[0-9.]+).jar' | grep -Eo '([-.a-z+_0-9+\]+[0-9]+)'

.Find | xargs | ln | Grep
 find ~/.m2/repository/ -type f -regextype posix-extended -regex '^[./].*[.][0-9]+[.]jar$' | sort -d | xargs -i ln -s {} $(echo {} | grep -Eo '([-a-z+]+[0-9.]+).jar$' | grep -Eo '([-.a-z+_0-9+\]+[0-9]+)' )


=== Grep Text with - `grep`

.?
[source,bash]
----
???
----

==== With `-E, --extended-regexp`

=== jq - Json Query

[source,bash]
.Restructure Output of `ls -al` into a JSON
----
{(echo -e 'c1 c2 c3 c4 c5 c6 c7 c8 c9' & (ls -al ../ | tail -n +2)) } | cat - |
  tr -s ' ' |
    jq -Rcn '
    input   | split(" ")  as $header |
    inputs  | split(" ") |
                    to_entries |
                            map(.key = $header[.key]) | .[0:] | from_entries'
----

[source,bash]
.Restructure Output of Text file into a JSON - Feed to `wget`
----
{(echo -e 'url filename' & (cat url-filename.txt)) } | cat - |   tr -s ' ' |     jq -Rcn '
    input   | split(" ")  as $header |
    inputs  | split(" ") |
                    to_entries |
                            map(.key = $header[.key]) | .[0:] | from_entries' | jq -r '"\(.filename) \(.url)"' | xargs -L 1 bash -c  'wget -O $0 $1'
----
[source,bash]
.Print Path and Key Values of a JSON
----
cat somejson.json | jq -r 'paths(scalars | true) as $p  | [ ( [ $p[] | tostring ] | join(".") ), ( getpath($p) | tojson )] | join(": ")'
----



=== ThinkFan

.`thinkfan`
[source,bash]
----
seq 1 8 | xargs -i bash -c "printf {}'--> ' ;  cat /sys/devices/platform/thinkpad_hwmon/hwmon/hwmon5/temp{}_input"
----

.`thinkfan`
[source,bash]
----
find /sys -type f -regextype posix-extended -regex '^(.|./).*(hwmon).*' | jq -R 'split("\n") | .[]'| grep -iE 'temp' | xargs -i bash -c 'echo -n {}": "; cat {}'
----

.`thinkfan`
[source,bash]
----
find /sys -type f -regextype posix-extended -regex '^(.|./).*(hwmon).*' | jq -R 'split("\n") | .[]'| grep -iE 'temp' | xargs -i bash -c 'printf {}" : "; cat {}' | jq -R 'split(" : ")'|jq -s 'to_entries'
----

.`thinkfan`
[source,bash]
----
find /sys -type f -regextype posix-extended -regex '^(.|./).*(hwmon).*' | jq -R 'split("\n") | .[]'| grep -iE 'temp' | xargs -i bash -c 'printf {}" : "; cat {}' | jq -R 'split(" : ")'|jq -s 'to_entries as $p | $p[] | to_entries as $c | $c | {'i':.[0].value, 'path':.[1].value[0], 'content':.[1].value[1]}'
----

=== XClip

.`xclip` - copy from terminal
[source,bash]
----
echo "whatever-command-to-be-copiedto-clipabord" | xclip -selection clipboard
----

=== GIO commandline tool - `gio`

.gio command manual
 man gio

.List Google Drive Mount
 gio list -d

NOTE: `-d` to list with files description name

=== Multiple Virtual Webcams - OBS & Iriun

.install v4l2
 sudo apt install v4l2loopback-dkms
 sudo apt install v4l-utils

 v4l2-ctl --list-devices

.Links used:

* https://obsproject.com/forum/threads/new-virtual-cam-choose-device.137869/[OBS Studio]
* https://askubuntu.com/questions/1385319/irium-webcam-initialization-failed[Ask Ubuntu]


.Steps:

. List All `v4l2` Devices
+
----
v4l2-ctl --list-devices
----

. Remove the `v4l2loopback` Module:
+
----
sudo rmmod v4l2loopback
----

. Edit (using sudo) the file `/etc/modprobe.d/iriunwebcam-options.conf`
+
----
options v4l2loopback exclusive_caps=1 devices=2 video_nr=8,9 card_label="OBS Virtualcam,Iriun Webcam"
options snd-aloop index=1
----
+
NOTE: Don't change the number at snd-aloop line: it is specific to your system (in my case it is 1). Watch for video_nr numbers. Be sure you are not using one already in use (check it --- no need for sudo --- in terminal: v4l2-ctl --list-devices)


. Edit (using sudo) the file `/etc/modules-load.d/iriunwebcam.conf`
+
----
v4l2loopback
options v4l2loopback video_nr=8,9
options v4l2loopback card_label="OBS Virtualcam,Iriun Webcam"
snd-aloop
----
+
NOTE: Use the same parameters as in the previous file for video_nr and card_label (not sure if it is mandatory, I've not checked this). This file ensures that Ubuntu will load these two virtual video devices at startup.

. I'm not sure if the next (and final) step is needed or just a system reboot is good enough. But before rebooting Ubuntu, I did in terminal:
+
[source,bash]
----
sudo update-initramfs -u
----

=== AMD Graphics Driver - `amdgpu-install`

[source,bash]
----
amdgpu-install -y --accept-eula --usecase=graphics --vulkan=amdvlk --opencl=rocr
----

.Install via ROCm - (_Don't use unless the other one is broken_)
[source,bash]
----
amdgpu-install --usecase=graphics,rocm --opengl=mesa --opencl=rocr --vulkan=amdvlk
----

.Verify Installation
[source,bash]
----
dkms status
clinfo
rocminfo
glxinfo -B
eglinfo -B
----



.EDID (External Display Identification Data)
[source,bash]
----
find /sys/class/drm/card*/edid
----


- Reference -> https://wiki.archlinux.org/title/Variable_refresh_rate#Change_VRR_range_of_a_FreeSync_monitor[Change_VRR_range_of_a_FreeSync_monitor]

// ToDo
.Issues with `ghmbeldphafepmbegfdlkpapadhbakde`
----
./IndexedDB/chrome-extension_ghmbeldphafepmbegfdlkpapadhbakde_0.indexeddb.leveldb/LOG
./IndexedDB/chrome-extension_ghmbeldphafepmbegfdlkpapadhbakde_0.indexeddb.leveldb/LOG.old
./IndexedDB/chrome-extension_ghmbeldphafepmbegfdlkpapadhbakde_0.indexeddb.leveldb/LOCK
./Managed Extension Settings/ghmbeldphafepmbegfdlkpapadhbakde/LOG
./Managed Extension Settings/ghmbeldphafepmbegfdlkpapadhbakde/CURRENT
./Managed Extension Settings/ghmbeldphafepmbegfdlkpapadhbakde/MANIFEST-000001
./Managed Extension Settings/ghmbeldphafepmbegfdlkpapadhbakde/000003.log
./Managed Extension Settings/ghmbeldphafepmbegfdlkpapadhbakde/LOCK
./Local Extension Settings/ghmbeldphafepmbegfdlkpapadhbakde/LOG
./Local Extension Settings/ghmbeldphafepmbegfdlkpapadhbakde/CURRENT
./Local Extension Settings/ghmbeldphafepmbegfdlkpapadhbakde/MANIFEST-000001
./Local Extension Settings/ghmbeldphafepmbegfdlkpapadhbakde/000003.log
./Local Extension Settings/ghmbeldphafepmbegfdlkpapadhbakde/LOCK
./Sync Extension Settings/ghmbeldphafepmbegfdlkpapadhbakde/LOG
./Sync Extension Settings/ghmbeldphafepmbegfdlkpapadhbakde/CURRENT
./Sync Extension Settings/ghmbeldphafepmbegfdlkpapadhbakde/MANIFEST-000001
./Sync Extension Settings/ghmbeldphafepmbegfdlkpapadhbakde/000003.log
./Sync Extension Settings/ghmbeldphafepmbegfdlkpapadhbakde/LOCK
----




=== Open Sockets/Ports

[source,bash]
----
ss -natp
----

[source,bash]
----
ss -neopa
----


=== Listing Hardware/Devices/Products/Vendors & their Class/Buses/Speed

sudo lshw  | grep -iE '''|5000|speed|anker|hitachi|Renesas|hub|android|brio|C310|GenesysLogic|yeti|plantronics'


sudo lshw -short
sudo lshw -class bus -class disk

.List All Classes
sudo lshw -json | jq -r 'include "m"; .children | pv' | grep -i class | jq -Rr 'split(": ") | .[1]' | jq -sr 'unique | sort'


=== Unclaimed Network PCIE

[source,json]
----
{
    "id" : "network",
    "class" : "network",
    "handle" : "PCI:0000:22:00.0",
    "description" : "Network controller",
    "product" : "MEDIATEK Corp.",
    "vendor" : "MEDIATEK Corp.",
    "physid" : "0",
    "businfo" : "pci@0000:22:00.0",
    "version" : "00",
    "width" : 64,
    "clock" : 33000000,
    "configuration" : {
      "latency" : "0"
    },
    "capabilities" : {
      "pciexpress" : "PCI Express",
      "msi" : "Message Signalled Interrupts",
      "pm" : "Power Management",
      "bus_master" : "bus mastering",
      "cap_list" : "PCI capabilities listing"
    }
  }
----

----
-network UNCLAIMED
       description: Network controller
       product: MEDIATEK Corp.
       vendor: MEDIATEK Corp.
       physical id: 0
       bus info: pci@0000:22:00.0
       version: 00
       width: 64 bits
       clock: 33MHz
       capabilities: pciexpress msi pm bus_master cap_list
       configuration: latency=0
       resources: memory:dfc00000-dfdfffff memory:dfef8000-dfefffff
----

=== Proton Pass - Vaults

.Extract credentials for a pinned account
----
cat data.json | jq 'include "m"; .vaults
      | to_entries
      | .[].value
      | select(.name | ascii_downcase | contains( "VAULT_NAME"))
      | .items[]
      | select(.pinned == true)
      | .data.content
      | select(.itemUsername | ascii_downcase | contains( "USERNAME"))
      | .password'
----

.TBD
----
cat ./data.json   | jq -r 'include "m"; .vaults
    | to_entries
    | .[].value
    | select(.name | ascii_downcase | contains( "VAULT_NAME"))
    | .items[].data
    | select (.metadata.name | ascii_downcase | contains( "KEYWARD"))'
----

=== python venv

.error: externally-managed-environment
****


× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
python3-xyz, where xyz is the package you are trying to
install.

    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.

    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.

    See /usr/share/doc/python3.12/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
****


=== Bluetooth

.Find Bluetooth version aka (HCI & LMP)
----
hciconfig -a
----

.Query Bluetooth devices
----
bluetoothctl devices
hcitool info MAC_ADD

hcitool
hcitool dev
hcitool scan
hcitool lescan
hcitool leinfo
----

=== vdhcoapp

----
curl -sSLf https://github.com/aclap-dev/vdhcoapp/releases/latest/download/install.sh | bash
W: flatpak not installed. It is not necessary to install it, but if you're using Ubuntu (and derivatives), we recommend to install it to solve some CoApp registrations issues.
Skipping flatpak install
Downloading: https://github.com/aclap-dev/vdhcoapp/releases/latest/download/vdhcoapp-linux-x86_64.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 52.8M  100 52.8M    0     0  9847k      0  0:00:05  0:00:05 --:--:-- 10.9M
Extracting tarball…
/tmp/vdhcoapp-TuKNrx: bzip2 compressed data, block size = 900k
Registering CoApp
Installing…
Writing /home/haze/.mozilla/native-messaging-hosts/net.downloadhelper.coapp.json
Writing /home/haze/.var/app/org.mozilla.firefox/.mozilla/native-messaging-hosts/net.downloadhelper.coapp.json
Writing /home/haze/.config/BraveSoftware/Brave-Browser/NativeMessagingHosts/net.downloadhelper.coapp.json
VdhCoApp : VdhCoApp is ready to be used
CoApp successfuly installed under '~/.local/share/vdhcoapp'.
To uninstall, run '~/.local/share/vdhcoapp/vdhcoapp uninstall' and remove '~/.local/share/vdhcoapp'.
Re-run that script to update the coapp.
----


== `hplip` - Installation

.build
----
tar -xvif hplip-3.24.4.tar.gz
cd hplip-3.24.4

./configure
make
make install
----

.Alternative - run `./hplip-install`
----
tar -xvif hplip-3.24.4.tar.gz
cd hplip-3.24.4

./hplip-install
----

=== troubleshooting

.configure: error: cannot find net/ucd-snmp support
 sudo apt-get install libsnmp-dev

.configure: error: cannot find avahi_client support
 sudo apt-get install libavahi-client-dev

.configure: error: cannot find libcups support
 sudo apt-get install libcups2-dev

.configure: error: cannot find sane-backends-devel support
 sudo apt install libsane-dev

.prnt/cupsext/cupsext.c:78:10: fatal error: Python.h: No such file or directory
 make clean
 ./configure
 make

./usr/bin/ld: cannot find -lavahi-core: No such file or directory
 sudo apt-get install libavahi-core-dev

.CUPSEXT could not be loaded. Please check HPLIP installation.

.Gtk-Message: 09:18:48.486: Failed to load module "canberra-gtk-module"
 sudo apt-get install libcanberra-gtk-module

.warning: Failed to read /etc/cups/ppd/OfficeJet_250_Mobile.ppd ppd file
 TBD

== `strace` - trace system calls and signals

----
strace echo "hi"
----