:toc:
:toclevels: 3
:sectnums: 3
:sectnumlevels: 3
:icons: font
:source-highlighter: rouge
== Brave Browser - Developer's Guide to Inspecting & Debugging




=== Backup & Syncing - `rsync`

.Profile Name (not dir name)
[source,bash]
 find $HOME/.config/BraveSoftware/*/*/Preferences | xargs -i jq --arg path "{}" '{path: $path, profile_name: .profile.name}' "{}"






.Profile Dir Name
[source,bash]
 cat $HOME/.config/BraveSoftware/Brave-Browser/Local\ State | jq -r 'include "m"; pv' | grep -iE PROFILE_DIR_NAME

[source,bash]
 cat $HOME/.config/BraveSoftware/Brave-Browser/Local\ State | jq -r 'include "m"; .profile.info_cache'

.Create a New Profile
[source,bash]
 brave-browser --profile-directory="PROFILE_DIR_NAME"

.Initiate a New Brave with a New Profile
[source,bash]
----
BRAVE_HOME_NEW=$HOME/temp-brave
PROFILE_DIR_NAME=Profile@Therapy
brave-browser --user-data-dir=$BRAVE_HOME_NEW --profile-directory=$PROFILE_DIR_NAME
----


.Profile-Only Full Backup - `rsync`
[source,bash]
----
rsync -avzhruP --delete
  --include='brave-browser*'
  --include='brave-browser*/Profile@*'
  --exclude='brave-browser*/*'
  $HOME/.config/BraveSoftware $HOME/.config/BraveSoftware.Profiles.2 -n
----

.Profile-Only Full Backup - `rsync`
[source,bash]
----
rsync -avzhruP --delete \
  --include="brave-browser*" \
  --include="brave-browser*/Local State" \
  --include="brave-browser*/First Run" \
  --include="brave-browser*/Profile@*" \
  --exclude="brave-browser*/*" \
  --exclude="brave-browser*/Profile@*/.org.chromium.*" \
  ${HOME}/.config/BraveSoftware/ ${HOME}/.config/BraveSoftware.profiles/ -n
----


.Profiles-Only Selective Backup - `rsync`
[source,bash]
----
rsync -avzhruP --delete \
  --include="brave-browser*/" \
  --include="brave-browser*/Local State" \
  --include="brave-browser*/First Run" \
  --include="brave-browser*/Profile@*" \
  --exclude="brave-browser*/Profile@*/.org.chromium.*" \
  --include="brave-browser*/Profile@*/Extensions" \
  --include="brave-browser*/Profile@*/Bookmarks*" \
  --include="brave-browser*/Profile@*/Custom Dictionary.txt" \
  --include="brave-browser*/Profile@*/Preferences" \
  --include="brave-browser*/Profile@*/Shared Dictionary" \
  --include="brave-browser*/Profile@*/Top Sites*" \
  --include="brave-browser*/Profile@*/Visited Links" \
  --include="brave-browser*/Profile@*/Web Data*" \
  --include="brave-browser*/Profile@*/Extensions" \
  --exclude="brave-browser*/Profile@*/*" \
  --exclude="brave-browser*/*" \
  ${HOME}/.config/BraveSoftware/ ${HOME}/.config/BraveSoftware.profiles.selective/ -n


#  --include="brave-browser*/Profile@*/Shortcuts.*" \
#  --include="brave-browser*/Profile@*/Favicons.*" \
#  --include="brave-browser*/Profile@*/Cookies.*" \
----

=== Extensions Management


.Find the Hashes of Extensions
[source,bash]
----
find .config/BraveSoftware/brave-browser-*/ \( -not -iregex '.*Profile\@.*' -regex '.*json'  \) -type f  \( -exec grep -iEl '.*ghmbel.*' {} \;  \) \
    | xargs -i jq --arg P {} '. + {path: $P}' {} \
    | jq -s ' map(. as $i | $i.hashes | to_entries
              | { path: $i.path,
                        manifest: map(  { hash: .key,
                                          appid: .value.appid | select(contains(""))
                                        })
                } )'
----

.Find All Extensions in All Profiles (name + path)
[source,bash]
----
KW=session; \
find ${HOME}/.config/BraveSoftware/brave-browser-*/Profile@*/Extensions/*/*/manifest.json \
    | xargs -i jq --arg path "{}" \
      '{short_name: .short_name,
          name: .name, path: $path,
          pathSplits: $path|split("/")
      }' {} \
    | jq --arg kw $KW 'select([.name, .short_name] | tostring | test($kw; "ig"))'; \
KW=;
----




//ToDo - Bad
.Find All Extensions in All Profiles (name + path)
[source,bash]
----
KW=SOME_KW; \
for P in $(find "${HOME}"/.config/BraveSoftware/brave-browser-*/Profile@*/Extensions/*/*/manifest.json);
  do
  A=$(echo $P | grep -iE 'Extensions/.*json' -o | grep -iE '\/\w+/' -o | grep -iE '\w+' -o);

#  echo $A:$P

  cat $P | jq --arg path $P --arg extid $A '{short_name: .short_name, name: .name, extid: $extid, path: $path}' \
  | jq --arg kw "${KW}" 'select([.name, .short_name] | tostring | test($kw; "ig"))';
done; \
KW=;
----

//ToDo
.Find All Files Of Type JSON - `file`?
[source,bash]
----
KW=SOME_KW;find "${HOME}"/.config/BraveSoftware/brave-browser-*/ -regextype posix-extended -iregex '.*' -type f -exec file {} + \
  | jq -Rr 'split(":") | select(.[1] | test("json"; "gi")) | {p:.[0]} ' \
  | jq -r '.p' \
  | xargs -i grep -iE $KW {};
KW=SOME_KW;
----

.As a function with Args
[source,bash]
----
brave-find-files-with-kw-fun () {
    P=$1; \
    FTYPE=$2; \
    KW=$3; \
    find ${P} -regextype posix-extended -iregex '.*' -type f -exec file {} + \
      | grep --color=auto -i "${FTYPE}" \
      | jq --arg FT "${FTYPE}" -R 'split(":") | map(.|sub("^[ ]+|[ ]+$"; "")) | {path: .[0], type: .[1] | capture("(?<d>" + $FT + ")"; "i") | .d | ascii_downcase}' \
      | jq '.path' \
      | xargs grep $KW -l \
      | xargs -i echo {}:$KW \
      | jq -R 'split(":") | {path: .[0], keyword: .[1]}'
}
----

.One way to use this function
====
[source,bash]
----
brave-find-files-with-kw-fun "${HOME}/.config/BraveSoftware/brave-browser-*/" json ghmbeldphafepmbegfdlkpapadhbakde
----
====


.Find All Files Of Type JSON - `file`?
[source,bash]
----
KW=ghmbeldphafepmbegfdlkpapadhbakde; \
find "${HOME}"/.config/BraveSoftware/brave-browser-*/ -regextype posix-extended -iregex '.*' -type f -exec file {} + \
  | grep -i json \
  | jq --arg FT "${FTYPE}" -R 'split(":") | map(.|sub("^[ ]+|[ ]+$"; "")) | {path: .[0], type: .[1] | capture("(?<d>" + $FT + ")"; "i") | .d | ascii_downcase}' \
  | jq '.path' \
  | xargs grep $KW -l \
  | xargs -i echo {}:$KW \
  | jq -R 'split(":") | {path: .[0], keyword: .[1]}'
----


.Possible Variables
CAUTION: Consider these Vars: +
$PATH
$KW_P
$KW_C
$FTYPE


.macs
[source,bash]
----
while true; \
  do cat ${HOME}/.config/BraveSoftware/brave-browser-experiment/Profile@Experiment/Preferences \
  | jq '.protection.macs.extensions.settings.ghmbeldphafepmbegfdlkpapadhbakde'; \
  sleep 1; \
done
----


.Finding Paths with Operations `group_by` `to_entries` `join` `map` (modified)
[source,bash]
----
KW=ghmbeldphafepmbegfdlkpapadhbakde; \
find  brave-browser-*/Profile@*/Extensions/$KW/1.31.1_0/ -type f \
  | jq -R 'split("/") | {profile: .[1], paths: .[4:] | join("/")}' \
  | jq -s 'group_by(.profile) | to_entries | map({profile: .value[0].profile, paths: [.value[].paths] | sort}) ' \
  | jq '  .[] as $arr1 |
          .[] as $arr2 |
          foreach $arr1 as $i (0; foreach $arr2 as $j (0; {profiles: ($i.profile + " - " + $j.profile) , diff: ($i.paths - $j.paths)}))';
----



.Finding Paths with Operations `group_by` `to_entries` `join` `map` (modified)
[source,bash]
----
KW=ghmbeldphafepmbegfdlkpapadhbakde; \
find brave-browser-*/Profile@*/Extensions/$KW/1.31.1_0/ -type f \
  | jq -R 'split("/") | {profile: .[1], abspath: .[0:5] | join("/"), paths: .[4:] | join("/")}' \
  | jq -s 'group_by(.profile) | to_entries | map({abspath: .value[0].abspath, profile: .value[0].profile, paths: [.value[].paths] | sort}) ' \
  | jq ' .[] as $arr1 |
         .[] as $arr2 |
         foreach $arr1 as $i (0; foreach $arr2 as $j (0; {path: $j.abspath, profiles: ($i.profile + " - " + $j.profile) , diff: ($i.paths - $j.paths)}))' \
  | jq 'select(isempty(.diff[]) == 'false')';
----



.Finding Paths with Operations `group_by` `to_entries` `join` `map` (modified)
[source,bash]
----

BASE_PATH=;
SRC_PATH=;
TRG_PATH=;
KW_IN_FILE=;
KW_IN_PATH_COMMON=;
BASE_PATH_RANGE=;
DIFF_PATHS_RANGE=;



fun-diff-dirs-with-similar-paths() {
    find ${HOME}/.config/BraveSoftware/brave-browser-*/Profile@*/*/$KW -type f   \
      | jq -R 'split("/") | {profile: .[6], abspath: .[0:-1] | join("/"), paths: .[-1] }'  \
      | jq -s 'group_by(.profile) | to_entries | map({abspath: .value[0].abspath, profile: .value[0].profile, paths: [.value[].paths] | sort}) '   \
      | jq ' .[] as $arr1 |
             .[] as $arr2 |
             foreach $arr1 as $i (0; foreach $arr2 as $j (0; {path: $j.abspath, profiles: ($i.profile + " - " + $j.profile) , diff: ($i.paths - $j.paths)}))' \
      | jq 'select(isempty(.diff[]) == 'false')';}
----



.Loop through Extension's Last Modified Timestamp
[source,bash]
include::../../utils/data-mining/jq-brave-ext-reset.sh[tag=fun_brave_check_extension_dir]


.Join every 3 lines together
[source,bash]
----

----













.Select Paths of a KW - With -s
----
----

..Select Paths of a KW - Without -s
----
----


