== GPG - Quick Guide
:toc:
:toclevels: 3
:sectnums: 3
:sectnumlevels: 3
:icons: font
:source-highlighter: rouge

=== Symmetric Encryption/Decryption

.Encrypt via default cipher:
 gpg -c file

.Decrypt and output to STDOUT:
 gpg -d file.gpg

.Decrypt and output to FILE:
 gpg -d -o outfile file.gpg

.You can choose the symmetric cipher:
TIP: `gpg -c --cipher-algo AES256`

.Default cipher is:
NOTE: `AES128`

=== Asymmetric Encryption/Decryption

.List Keys
 gpg --list-keys

.Generate Keys
 gpg --full-generate-keys

.Encrypt
 gpg -e --recipient email_id file

.Decrypt and output to STDOUT:
 gpg -d file.gpg

.Decrypt and output to FILE:
 gpg -d -o outfile file.gpg

==== Export/Import Keys

.Export private key
 gpg --export-secret-key --armor --output husain-private.key --recipient email_id

.Export public key
 gpg --export-key --armor --output husain-pub.key --recipient email_id

.Import Keys
 gpg --import secret_key

.ToDo - Confirm this:
NOTE: Importing secret keys will import the public key as well!

=== Guide

TIP: This is to provide the PASSPHRASE from the environment

.Encrypt
[source, bash]
----
gpg -v --passphrase $GPG_PASSPHRASE --batch --yes -o ENC-FILE.txt.gpg -c DEC-FILE.txt
----

.Encrypt - Automated
[source, bash]
----
find ./ -type f -regextype posix-extended -regex "^(../|./|/).*(_env-)*.properties$" \
  | xargs -i gpg -v --passphrase $GPG_PASSPHRASE --batch --yes -o {}.gpg -c {}
----



.Decrypt
[source, bash]
----
gpg -v --passphrase $GPG_PASSPHRASE --yes --batch -o DEC-FILE.txt -d ENC-FILE.txt.gpg
----

.Decrypt - Automated
[source, bash]
----
find ./ -type f -regextype posix-extended -regex "^(../|./|/).*(_env-)*.properties.gpg$" \
  | grep -o '.*[^.gpg]' \
  | xargs -i gpg -v --passphrase $GPG_PASSPHRASE --yes --batch -o {} -d {}.gpg
----