:toc:
:toclevels: 3
:sectnums: 3
:sectnumlevels: 3
:icons: font
:source-highlighter: rouge
== ffmpeg - Quick Guide



=== Installation

.Links
* https://trac.ffmpeg.org/wiki/CompilationGuide/Generic[Generic]
* https://trac.ffmpeg.org/wiki/CompilationGuide[CompilationGuide]
* https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu[Install from Source - Ubuntu]
* https://github.com/FFmpeg/FFmpeg/blob/master/INSTALL.md[Install from Binary - Deb]
* https://hub.docker.com/r/jrottenberg/ffmpeg/[Docker Image]


//   --bindir="$HOME/bin" \
//   --enable-gnutls \
//   --enable-libaom \
//   --enable-libass \
//   --enable-libfreetype \


.Enable Flag `--enable-gnutls`
https://gitlab.com/gnutls/gnutls/-/tree/master

.Test Failure around this
 sudo apt install unbound


.PreReqs- `apt-get`
[source,bash]
----
include::_etc/ffmpeg-install.sh[tags]
----



.Configure & Install
[source,bash]
----
./configure \
  --prefix="$FFMPEG_HOME/ffmpeg_build" \
  --pkg-config-flags="--static" \
  --extra-cflags="-I$PWD/ffmpeg_build/include" \
  --extra-ldflags="-L$PWD/ffmpeg_build/lib" \
  --extra-libs="-lpthread -lm" \
  --ld="g++" \
  --enable-gpl \
  --enable-libfdk-aac \
  --enable-libmp3lame \
  --enable-libopus \
  --enable-libsvtav1 \
  --enable-libdav1d \
  --enable-libvorbis \
  --enable-libvpx \
  --enable-libx264 \
  --enable-libx265 \
  --enable-nonfree && \
make && \
make install
----


.extra - might need build from source for all of them
----
--enable-chromaprint --enable-frei0r --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libdc1394 --enable-libdrm --enable-libfdk-aac --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libharfbuzz --enable-libiec61883 --enable-libjack --enable-libjxl --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libplacebo --enable-libpulse --enable-librabbitmq --enable-librav1e --enable-librist --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpl --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-nonfree --enable-openal --enable-opencl --enable-opengl --enable-pocketsphinx --enable-sdl2 --enable-shared
----




=== Usage

.Create Video From Multiple Pictures
[source,bash]
----
ffmpeg -framerate 25 -pattern_type glob  -i '*.png' -c:v libx264 -profile:v high -crf 20 -pix_fmt yuv420p -vf 'pad=ceil(iw/2)*2:ceil(ih/2)*2' -y output.mp4
----


.Combine Video and Audio
[source,bash]
----
ffmpeg -i input-video.mp4 -i input-audio.mp4 output.mp4
----

.Combine Video and Audio
[source,bash]
----
ffmpeg -i input-video.mp4 -i input-audio.mp4 -c:v copy -c:a copy -map_metadata -1 output.mp4
----

.Mix Multiple Audio Tracks from a Single Input File | `-filter_complex` `amix`
[source,bash]
----
ffmpeg -i INPUT.mkv -filter_complex "[0:a:0][0:a:1]amix=2:longest[aout]" -map "[aout]" -map 0:v -c:v libx264 OUTPUT.mp4
----


.Trim from/to time
----
ffmpeg -i INPUT.mkv -ss 00:00:00 -t 00:11:47 -c copy OUTPUT.mkv
----

.Concatenate Multiple Videos
----
$ cat mylist.txt
file '/path/to/file1'
file '/path/to/file2'
file '/path/to/file3'

$ ffmpeg -f concat -i mylist.txt -c copy output.mp4
----

=== Query Metadata

.ImageMagic - `identify`
 identify -verbose media_src | yq

.`exiftool`
 sudo apt install exiftool
 exiftool -json media_src


=== Reduce Video Size

To reduce the size of an MP4 file using FFmpeg, you can re-encode it with a lower bitrate or change the codec.
For example, you can use the command

 ffmpeg -i input.mp4 -c:v libx264 -crf 23 output.mp4

where -crf controls the quality and file size (lower values mean better quality).

.Links:
- https://unix.stackexchange.com/questions/28803/how-can-i-reduce-a-videos-size-with-ffmpeg
- https://www.mux.com/articles/how-to-compress-video-files-while-maintaining-quality-with-ffmpeg
- https://www.gumlet.com/learn/ffmpeg-compress-video/


==== Basic Compression Techniques

Change Video Codec
Using a more efficient codec can significantly reduce file size. The H.264 codec is widely compatible and offers good compression.
Command:
 ffmpeg -i input.mp4 -c:v libx264 -pix_fmt yuv420p output.mp4

Adjust Bitrate
Lowering the bitrate reduces file size but may affect quality. A bitrate of around 1000 kbps is often a good balance.
Command:
 ffmpeg -i input.mp4 -b:v 1000k output.mp4

Use Constant Rate Factor (CRF)
The CRF setting allows you to control the quality versus size. A CRF value between 23 and 28 is recommended for good quality.
Command:
 ffmpeg -i input.mp4 -c:v libx264 -crf 28 output.mp4


==== Advanced Techniques

Reduce Resolution
Lowering the resolution can also decrease file size. For example, changing to 720p is effective for mobile viewing.
Command:
 ffmpeg -i input.mp4 -vf scale=1280:720 output.mp4

Change Frame Rate
Reducing the frame rate can help decrease the size. Common frame rates are 30 fps or 24 fps.
Command:
 ffmpeg -i input.mp4 -r 24 output.mp4

Summary of Commands
Technique	Command Example

Change Video Codec	ffmpeg -i input.mp4 -c:v libx264 output.mp4
Adjust Bitrate	ffmpeg -i input.mp4 -b:v 1000k output.mp4
Use Constant Rate Factor	ffmpeg -i input.mp4 -crf 28 output.mp4
Reduce Resolution	ffmpeg -i input.mp4 -vf scale=1280:720 output.mp4
Change Frame Rate	ffmpeg -i input.mp4 -r 24 output.mp4
These methods will help you effectively reduce the size of your MP4 files while maintaining acceptable quality.