== `ipvlan`, `macvlan`, `veth` - Quick Guide
:toc:
:toclevels: 3
:sectnums: 3
:sectnumlevels: 3
:icons: font
:source-highlighter: rouge

=== VirtualBox | Local Network | netplan
sudo ip address add 192.168.1.100/24 dev enp0s8
sudo ip link set dev wlp34s0 enp0s8

.Deleting IP Address
sudo ip address del 192.168.1.100/24 dev enp0s8




=== vpn | vopono | namespace

.Deleting Connection
nmcli c delete DEVICE_NAME

.Restarting Network
nmcli n [on|off]

.Deleting Device
ip link delete dev DEVICE_NAME

.connect via an established tunnel tun0
vopono -v exec -i tun0 --provider VPN_PROVIDER --server SERVER_NAME bash

.deleting a dead link
----
ip link show
sudo ip link delete LINKNAME
----

.Example
NOTE: LINKNAME is namespace created by vopono




=== Disabling IPv6

.https://protonvpn.com/support/browser-extensions/[browser-extensions]
Can I use the Proton VPN app and the browser extension together?

Yes. If you use the Proton VPN app and the browser extension together, all your device’s internet connections are routed through the VPN server the app is connected to. Connections inside the browser, however, will then also be routed to the VPN server the browser extension is connected to. This creates a “double-VPN” effect similar to our Secure Core feature.

This setup can be useful. For example, you may wish to protect all your device’s connections by connecting to the fastest VPN server for your location. At the same time, you can stream content from another country in your browser.

Using our Secure Core feature will create a "triple-VPN" (or even a "quadruple-VPN" if used on both the browser extension and the VPN app), but the performance hit of doing this is likely to heavily outweigh any potential privacy and security advantages.



.https://protonvpn.com/support/disable-ipv6-protocol-linux/[disable-ipv6-protocol-linux]
How to manually disable IPv6 on Linux











.Deny IPv6 for an app
sudo addgroup no-ipv6

 sudo ip6tables --list
 sudo ip6tables -A OUTPUT -m owner --gid-owner no-ipv6 -j DROP
 sudo ip6tables --list

 sudo -g no-ipv6 _COMMAND_

.Persist ip6tables changes
 sudo ip6tables-save
 sudo ip6tables-restore

.You can easily write a wrapper script that uses sudo for you. You can get rid of the password prompt by adding
 sudo     ALL=(:no-internet)      NOPASSWD: ALL









 iwconfig - configure a wireless network interface

 ip route show

 ls /etc/netns/*







=== Split Tunnels





NS=v_ns

sudo ip netns add $NS
sudo ip netns exec $NS ip addr add 127.0.0.1/8 dev lo
sudo ip netns exec $NS ip link set lo up

#Appending to existing NetworkManager config file: /etc/NetworkManager/conf.d/unmanaged.conf

LINK=v_lnk
VETH=v_eth

IP_RANGE=10.200.1.0/24
IP_NS=10.200.1.1/24
IP_HOST=10.200.1.2/24
IP_GW=10.200.1.1

#IP_NS=192.168.1.50/24
#IP_HOST=192.168.1.51/24
#IP_GW=192.168.1.50

sudo ip link add $LINK type veth peer name $VETH
sudo ip link set $LINK up
sudo ip link set $VETH netns $NS up
sudo ip addr add $IP_NS dev $LINK
sudo ip netns exec $NS ip addr add $IP_HOST dev $VETH
sudo ip netns exec $NS ip route add default via $IP_GW dev $VETH
sudo nmcli connection reload


#Original IPs
sudo ip addr add 10.200.1.1/24 dev $LINK
sudo ip netns exec $NS ip addr add 10.200.1.2/24 dev $VETH
sudo ip netns exec $NS ip route add default via 10.200.1.1 dev $VETH
sudo nmcli connection reload

#IP address of namespace as seen from host: 10.200.1.2
#IP address of host as seen from namespace: 10.200.1.1



- iptable Rules

IF=wlp34s0
sudo iptables -t nat -A POSTROUTING -s $IP_RANGE -o $IF -j MASQUERADE
sudo iptables -I FORWARD -i $LINK -o $IF -j ACCEPT
sudo iptables -I FORWARD -o $LINK -i $IF -j ACCEPT
sudo sysctl -q net.ipv4.ip_forward=1


- DNS

#vopono_core::network::dns_config > Setting namespace $NS DNS server to 8.8.8.8

- Exec

sudo ip netns exec $NS sudo -u $USER bash


- If VPN will be used

sudo ip netns exec $NS openvpn --config /home/haze/.config/vopono/proton/openvpn/united_states-us.ovpn --machine-readable-output --log /home/haze/.config/vopono/logs/vo_pr_AnJcKro_openvpn.log --auth-user-pass /home/haze/.config/vopono/proton/openvpn/auth.txt --connect-retry-max 1 --pull-filter ignore block-outside-dns


- CleanUp

sudo ip link delete $LINK
sudo nmcli connection reload
sudo ip netns delete $NS
sudo nmcli connection reload

=== netplan