== Brave Browser - Developer's Guide to Inspecting & Debugging
:toc:
:toclevels: 3
:sectnums: 3
:sectnumlevels: 3
:icons: font
:source-highlighter: rouge



=== Backup & Syncing - `rsync`

.Profile Name (not dir name)
 find $HOME/.config/BraveSoftware/*/*/Preferences | xargs -i jq --arg path "{}" '{path: $path, profile_name: .profile.name}' "{}"






.Profile Dir Name
 cat $HOME/.config/BraveSoftware/Brave-Browser/Local\ State | jq -r 'include "m"; pv' | grep -iE PROFILE_DIR_NAME

 cat $HOME/.config/BraveSoftware/Brave-Browser/Local\ State | jq -r 'include "m"; .profile.info_cache'

.Create a New Profile
 brave-browser --profile-directory="PROFILE_DIR_NAME"

.Initiate a New Brave with a New Profile
----
BRAVE_HOME_NEW=$HOME/temp-brave
PROFILE_DIR_NAME=Profile@Therapy
brave-browser --user-data-dir=$BRAVE_HOME_NEW --profile-directory=$PROFILE_DIR_NAME
----


.Profile-Only Full Backup - `rsync`
[source,bash]
----
rsync -avzhruP --delete
  --include='brave-browser*'
  --include='brave-browser*/Profile@*'
  --exclude='brave-browser*/*'
  $HOME/.config/BraveSoftware $HOME/.config/BraveSoftware.Profiles.2 -n
----

.Profile-Only Full Backup - `rsync`
[source,bash]
----
rsync -avzhruP --delete \
  --include="brave-browser*" \
  --include="brave-browser*/Local State" \
  --include="brave-browser*/First Run" \
  --include="brave-browser*/Profile@*" \
  --exclude="brave-browser*/*" \
  --exclude="brave-browser*/Profile@*/.org.chromium.*" \
  ${HOME}/.config/BraveSoftware/ ${HOME}/.config/BraveSoftware.profiles/ -n
----


.Profiles-Only Selective Backup - `rsync`
[source,bash]
----
rsync -avzhruP --delete \
  --include="brave-browser*/" \
  --include="brave-browser*/Local State" \
  --include="brave-browser*/First Run" \
  --include="brave-browser*/Profile@*" \
  --exclude="brave-browser*/Profile@*/.org.chromium.*" \
  --include="brave-browser*/Profile@*/Extensions" \
  --include="brave-browser*/Profile@*/Bookmarks*" \
  --include="brave-browser*/Profile@*/Custom Dictionary.txt" \
  --include="brave-browser*/Profile@*/Preferences" \
  --include="brave-browser*/Profile@*/Shared Dictionary" \
  --include="brave-browser*/Profile@*/Top Sites*" \
  --include="brave-browser*/Profile@*/Visited Links" \
  --include="brave-browser*/Profile@*/Web Data*" \
  --include="brave-browser*/Profile@*/Extensions" \
  --exclude="brave-browser*/Profile@*/*" \
  --exclude="brave-browser*/*" \
  ${HOME}/.config/BraveSoftware/ ${HOME}/.config/BraveSoftware.profiles.selective/ -n


#  --include="brave-browser*/Profile@*/Shortcuts.*" \
#  --include="brave-browser*/Profile@*/Favicons.*" \
#  --include="brave-browser*/Profile@*/Cookies.*" \
----

=== Extensions Management


.Find All Extensions in All Profiles (name + path)
[source,bash]
----
KW=session; \
find ${HOME}/.config/BraveSoftware/brave-browser-*/Profile@*/Extensions/*/*/manifest.json \
    | xargs -i jq --arg path "{}" \
      '{short_name: .short_name,
          name: .name, path: $path,
          pathSplits: $path|split("/")
      }' {} \
    | jq --arg kw $KW 'select([.name, .short_name] | tostring | test($kw; "ig"))'; \
KW=;
----




//ToDo
.Find All Extensions in All Profiles (name + path)
[source,bash]
----
KW=session; \
for P in $(find "${HOME}"/.config/BraveSoftware/brave-browser-*/Profile@*/Extensions/*/*/manifest.json);
  do
  A=$(echo $P | grep -iE 'Extensions/.*json' -o | grep -iE '\/\w+/' -o | grep -iE '\w+' -o);

#  echo $A:$P

  cat $P | jq --arg path $P --arg extid $A '{short_name: .short_name, name: .name, extid: $extid, path: $path}' \
  | jq --arg kw "${KW}" 'select([.name, .short_name] | tostring | test($kw; "ig"))';
done; \
KW=;
----

//ToDo
.Find All Files Of Type JSON - `file`?
[source,bash]
----
KW=ghmbeldphafepmbegfdlkpapadhbakde;find "${HOME}"/.config/BraveSoftware/brave-browser-*/ -type f  -exec file {} + \
  | jq -Rr 'split(":") | select(.[1] | test("json"; "gi")) | {p:.[0]} ' \
  | jq -r '.p' \
  | xargs -i grep -iE $KW {};
KW=;
----


